# params.yaml
random_state: 42
test_size: 0.2

model:
  type: LinearRegression # or RandomForestRegressor
  fit_intercept: true

random_forest:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1

data:
  path: data/pakistan_house_prices.csv
  target: price
  features: [area, bedrooms, baths, city]
